name: JIB container publish

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - master
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: JIB container build and publish
        uses: pSub/jib-container-publish.yml@6048132e3c43e6257bfe1acdce328532c0c86807 # main
        with:
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          java-version: 21
          java-distribution: temurin
          module: cli
          main-class: de.redsix.dmncheck.cli.Main